complexity:
  ComplexCondition:
    active: false
  CyclomaticComplexMethod:
    active: false
  LongMethod:
    active: false
  LargeClass:
    active: false
  NestedBlockDepth:
    active: false
  TooManyFunctions:
    active: false

naming:
  FunctionParameterNaming:
    active: true
    parameterPattern: '`?[a-z][A-Za-z0-9]*`?'
  MatchingDeclarationName:
    active: false
  MemberNameEqualsClassName:
    active: false

potential-bugs:
  UnsafeCallOnNullableType:
    active: false

style:
  LoopWithTooManyJumpStatements:
    active: false
  MagicNumber:
    active: false
  MaxLineLength:
    active: true
    maxLineLength: 250
  ReturnCount:
    active: false
  UnusedPrivateMember:
    active: false
  UnusedPrivateProperty:
    active: false
